site_name: ECHOLab Hitchicker's Guide
repo_url: https://github.com/echolab-stanford/Hitchhikers-Guide-to-ECHOLab

theme:
  name: material
  locale: en
  highlightjs: true
  hljs_language: 
    - python
    - R
    - bash

nav:
  - Home: index.md
  - General advice:
    - 'computing.md'
    - 'palife.md'
    - 'resources.md'
  - Graduate students:
    - 'recs.md'
    - 'life.md'
  - Postdocs:
    - 'postdocs.md'
  - About: 
    - 'Us': 'whois.md'
    - 'Contribute to this doc': 'contribute.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      separator: "_"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

