site_name: ECHOLab Hitchhicker's Guide
repo_name: 'Github'
repo_url: 'https://github.com/echolab-stanford/Hitchhikers-Guide-to-ECHOLab'
site_url: 'https://echolab-stanford.github.io/Hitchhikers-Guide-to-ECHOLab/'
site_author: 'ECHOLab'

copyright: '&copy; 2023 ECHOLab'

extra:
  social: 
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/StanfordECHOLab
      name: Our twitter

theme:
  name: material
  locale: en
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - navigation.instant
    - navigation.path

nav:
  - Home: index.md
  - General advice:
    - 'computing.md'
    - 'palife.md'
    - 'resources.md'
    - 'expectations.md'
  - Graduate students:
    - 'recs.md'
    - 'life.md'
  - Postdocs:
    - 'postdocs.md'
  - About: 
    - 'Us': 'whois.md'
    - 'Contribute to this doc': 'contribute.md'

markdown_extensions:
  - toc:
      title: On this page
      toc_depth: 4
      permalink: "#"
      separator: "_"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - def_list
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji
plugins:
  - search: {}
  - encryptcontent:
      title_prefix: '🔒'
      password_button: true
      password_button_text: 'Decrypt'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

